"""Tests for pgloader compatibility — SQL patterns generated by pgloader.

pgloader connects directly to MySQL and writes to PostgreSQL, emitting SQL
that differs from standard mysqldump format. These tests verify that mysqlpg
can handle pgloader-style SQL statements for round-trip compatibility.
"""

import pytest
from mysqlpg.translator import translate


class TestPgloaderCreateType:
    """pgloader converts MySQL ENUM columns to PG CREATE TYPE ... AS ENUM."""

    def test_simple_enum(self, mock_conn):
        sql = "CREATE TYPE status_type AS ENUM ('active', 'inactive', 'deleted')"
        result, _ = translate(sql, mock_conn)
        assert "CREATE TYPE" in result
        assert "ENUM" in result

    def test_enum_with_special_chars(self, mock_conn):
        sql = "CREATE TYPE priority AS ENUM ('low', 'medium-high', 'critical!')"
        result, _ = translate(sql, mock_conn)
        assert result == sql

    def test_drop_type_if_exists(self, mock_conn):
        sql = "DROP TYPE IF EXISTS status_type CASCADE"
        result, _ = translate(sql, mock_conn)
        assert "DROP TYPE" in result

    def test_drop_type_simple(self, mock_conn):
        sql = "DROP TYPE my_type"
        result, _ = translate(sql, mock_conn)
        assert "DROP TYPE" in result


class TestPgloaderTriggerControl:
    """pgloader uses DISABLE/ENABLE TRIGGER ALL for bulk loading."""

    def test_disable_trigger_all(self, mock_conn):
        sql = "ALTER TABLE users DISABLE TRIGGER ALL"
        result, _ = translate(sql, mock_conn)
        assert "DISABLE TRIGGER ALL" in result

    def test_enable_trigger_all(self, mock_conn):
        sql = "ALTER TABLE users ENABLE TRIGGER ALL"
        result, _ = translate(sql, mock_conn)
        assert "ENABLE TRIGGER ALL" in result

    def test_disable_trigger_with_schema(self, mock_conn):
        sql = 'ALTER TABLE "public"."users" DISABLE TRIGGER ALL'
        result, _ = translate(sql, mock_conn)
        assert "DISABLE TRIGGER ALL" in result

    def test_disable_keys_still_noop(self, mock_conn):
        """MySQL DISABLE KEYS is different from PG DISABLE TRIGGER."""
        sql = "ALTER TABLE `users` DISABLE KEYS"
        _, is_special = translate(sql, mock_conn)
        assert is_special  # Still treated as no-op


class TestPgloaderCopyFromStdin:
    """pgloader uses COPY ... FROM STDIN for bulk data loading."""

    def test_basic_copy(self, mock_conn):
        sql = "COPY users (id, name, email) FROM STDIN"
        result, _ = translate(sql, mock_conn)
        assert "COPY" in result
        assert "FROM STDIN" in result

    def test_copy_with_options(self, mock_conn):
        sql = "COPY users FROM STDIN WITH (FORMAT csv, DELIMITER ',')"
        result, _ = translate(sql, mock_conn)
        assert "COPY" in result


class TestPgloaderIndexCreation:
    """pgloader creates indexes directly with CREATE INDEX."""

    def test_simple_index(self, mock_conn):
        sql = "CREATE INDEX idx_123_name ON users (name)"
        result, _ = translate(sql, mock_conn)
        assert "CREATE INDEX" in result

    def test_unique_index(self, mock_conn):
        sql = "CREATE UNIQUE INDEX idx_456_email ON users (email)"
        result, _ = translate(sql, mock_conn)
        assert "CREATE UNIQUE INDEX" in result

    def test_composite_index(self, mock_conn):
        sql = "CREATE INDEX idx_789_user_post ON comments (user_id, post_id)"
        result, _ = translate(sql, mock_conn)
        assert "CREATE INDEX" in result

    def test_backtick_index(self, mock_conn):
        sql = "CREATE INDEX `idx_name` ON `users` (`name`)"
        result, _ = translate(sql, mock_conn)
        assert '"idx_name"' in result
        assert '"users"' in result


class TestPgloaderConstraints:
    """pgloader adds FK constraints as ALTER TABLE ADD CONSTRAINT."""

    def test_foreign_key(self, mock_conn):
        sql = ("ALTER TABLE posts ADD CONSTRAINT fk_posts_user "
               "FOREIGN KEY (user_id) REFERENCES users (id)")
        result, _ = translate(sql, mock_conn)
        assert "ADD CONSTRAINT" in result
        assert "FOREIGN KEY" in result
        assert "REFERENCES" in result

    def test_fk_with_actions(self, mock_conn):
        sql = ("ALTER TABLE posts ADD CONSTRAINT fk_posts_user "
               "FOREIGN KEY (user_id) REFERENCES users (id) "
               "ON DELETE CASCADE ON UPDATE SET NULL")
        result, _ = translate(sql, mock_conn)
        assert "CASCADE" in result


class TestPgloaderSequenceReset:
    """pgloader resets sequences with SELECT setval(...)."""

    def test_setval(self, mock_conn):
        sql = "SELECT setval('users_id_seq', 100, true)"
        result, _ = translate(sql, mock_conn)
        assert "setval" in result

    def test_setval_false(self, mock_conn):
        sql = "SELECT setval('users_id_seq', 0, false)"
        result, _ = translate(sql, mock_conn)
        assert "setval" in result


class TestPgloaderSessionControl:
    """pgloader sets session_replication_role for FK bypass."""

    def test_replica_mode(self, mock_conn):
        sql = "SET session_replication_role = 'replica'"
        result, _ = translate(sql, mock_conn)
        assert "session_replication_role" in result

    def test_origin_mode(self, mock_conn):
        sql = "SET session_replication_role = 'origin'"
        result, _ = translate(sql, mock_conn)
        assert result == sql


class TestZeroDateConversion:
    """MySQL zero dates should be converted to NULL for PG compatibility."""

    def test_zero_datetime_in_insert(self, mock_conn):
        sql = ("INSERT INTO events (id, created_at) "
               "VALUES (1, '0000-00-00 00:00:00')")
        result, _ = translate(sql, mock_conn)
        assert "'0000-00-00 00:00:00'" not in result
        assert "NULL" in result

    def test_zero_date_in_insert(self, mock_conn):
        sql = "INSERT INTO events (id, birth_date) VALUES (1, '0000-00-00')"
        result, _ = translate(sql, mock_conn)
        assert "'0000-00-00'" not in result
        assert "NULL" in result

    def test_normal_date_preserved(self, mock_conn):
        sql = "INSERT INTO events (id, date) VALUES (1, '2024-01-15')"
        result, _ = translate(sql, mock_conn)
        assert "'2024-01-15'" in result

    def test_multiple_zero_dates(self, mock_conn):
        sql = ("INSERT INTO t VALUES "
               "(1, '0000-00-00', '0000-00-00 00:00:00', '2024-01-01')")
        result, _ = translate(sql, mock_conn)
        assert result.count("NULL") == 2
        assert "'2024-01-01'" in result


class TestPgloaderTypeMapping:
    """Test that pgloader-generated PG types are handled correctly."""

    from mysqlpg.translator import _map_mysql_type_to_pg

    def test_bigserial_from_auto_increment(self):
        """pgloader converts AUTO_INCREMENT to bigserial."""
        from mysqlpg.ddl import PG_TO_MYSQL_TYPE
        assert PG_TO_MYSQL_TYPE["bigserial"] == "bigint(20)"

    def test_smallserial(self):
        from mysqlpg.ddl import PG_TO_MYSQL_TYPE
        assert PG_TO_MYSQL_TYPE["smallserial"] == "smallint(6)"

    def test_boolean_tinyint(self):
        """pgloader converts tinyint(1) to boolean in PG."""
        from mysqlpg.ddl import PG_TO_MYSQL_TYPE
        assert PG_TO_MYSQL_TYPE["boolean"] == "tinyint(1)"


class TestMySQLDumpSetStatements:
    """Verify that SET statements from MySQL dumps are handled for
    pgloader round-trip (dump → mysqlpg → PG → pgloader → MySQL)."""

    def test_set_names(self, mock_conn):
        result, _ = translate("SET NAMES utf8mb4", mock_conn)
        assert "client_encoding" in result

    def test_set_fk_checks_off(self, mock_conn):
        result, _ = translate("SET FOREIGN_KEY_CHECKS = 0", mock_conn)
        assert "session_replication_role" in result

    def test_set_fk_checks_on(self, mock_conn):
        result, _ = translate("SET FOREIGN_KEY_CHECKS = 1", mock_conn)
        assert "origin" in result

    def test_lock_tables_noop(self, mock_conn):
        _, is_special = translate("LOCK TABLES `users` WRITE", mock_conn)
        assert is_special

    def test_unlock_tables_noop(self, mock_conn):
        _, is_special = translate("UNLOCK TABLES", mock_conn)
        assert is_special
